### ISSUE TITLE
How to simultaneously manually control the BlueROV2 and record data via rosbag?

### ISSUE THREAD

**Issue by phamquandung** [remaro-network/tudelft_hackathon#43]
Hi @Rezenders. Thanks for your great work. Currently I am interested in using BlueROV2 to record data in underwater. However when using QGC, and ping viewer to record video and sonar images, they can't go with timestamp so I try to look for another solution and I came to ROS. I am quite new to ROS as I have no experience before. I attempted to read through the forum of BlueROV2 and luckily I found your page. I would like to dig deeply into it. I successfully setup tudelft_hackathon. However there are no tutorials so it's quite hard for me to follow. 

I ran: ` ros2 launch tudelft_hackathon bluerov_bringup.launch.py simulation:=false`, but I do not know how to control the BlueROV2. I tried to plug in the joystick but nothing happened. I wonder if after running the aforementioned command, am I able to control the BlueROV2 mannually using joystick and then run rosbag to topics to record data? Also, if I can't do what I want with the aforementioned command, what should I do? As an expert, could you please recommend me any methods?  Thanks

**Comment by Rezenders** [comment]
Hi @phamquandung,

Sorry for not replying, I totally missed this issue.

Did you manage to find a solution?

> I tried to plug in the joystick but nothing happened. I wonder if after running the aforementioned command, am I able to control the BlueROV2 mannually using joystick and then run rosbag to topics to record data? 

That won't work, because the [agent_node](https://github.com/remaro-network/tudelft_hackathon/blob/c4034ebe8e98038a1fe7991b4c89c7fb9cbdbc82/launch/bluerov_bringup.launch.py#L63) is overriding the RC commands. So you won't be able to control it with the joystick via the GCS.

If you simply want to control the robot with a joystick via the GCS and record camera + sonar data, you don't need to run the agent_node and mavros. You can simply run the ping360 node + another node for the camera and record it with rosbag. This way you will be able to use the joystick with the GCS
