### ISSUE TITLE
[Bug] [ERROR] [launch]: Caught exception in launch (see debug for traceback): invalid syntax

### ISSUE THREAD

**Issue by phamquandung** [remaro-network/tudelft_hackathon#46]
Dear @Rezenders 

I try to run you updated code. There are several issue. 

First, in the line 57 of bluerov_bringup.launch.py, you should change: AnyLaunchDescriptionSource to PythonLaunchDescriptionSource. https://github.com/remaro-network/tudelft_hackathon/blob/1b8551e2daa44967b93a43b1f378a831ec44a9fc/launch/bluerov_bringup.launch.py#L57

Second, it seems like the symbol ' in line 3 of apm.lauch of mavros stops the program. I delete it but the new bug come up. [ERROR] [launch]: Caught exception in launch (see debug for traceback): invalid syntax (apm.launch, line 1)

Could you please help me to solve this issue?

Thanks

**Comment by Rezenders** [comment]
Hello @phamquandung,

Thanks for the bug report.

Actually, since apm.launch is not a python launchfile, we need to use `AnyLaunchDescriptionSource`. But for some reason, I deleted the import for that.
I added it again:
https://github.com/remaro-network/tudelft_hackathon/blob/c4034ebe8e98038a1fe7991b4c89c7fb9cbdbc82/launch/bluerov_bringup.launch.py#L11

I updated the versions of the ROS packages used as deps: https://github.com/remaro-network/tudelft_hackathon/blob/ros2/hackathon.rosinstall

So you should reinstall the `tudelft_hackathon_ws` from scratch, or just update the deps and rebuild.

```
cd ~/tudelft_hackathon_ws
rm hackathon.rosinstall
wget https://raw.githubusercontent.com/remaro-network/tudelft_hackathon/ros2/hackathon.rosinstall
vcs pull src < hackathon.rosinstall --nested
```

I also updated ardusub version, so you should reinstall it from scratch as well. I recommend deleting the whole ardupilot repo and getting it again.
```
cd ~/
rm -rf ardupilot
```
Then repeat the instructions: https://github.com/remaro-network/tudelft_hackathon#install-ardusub

I tested it now, and it worked with these patches. I will close the issue for now, let me know if you have any problems or questions.

**Comment by Rezenders** [comment]
And I changed the instructions to run the simulation, for some reason it is not working when ardusub + simulation are executed at the same time. So, just run both separately:

In one terminal run ardusub SITL:
```Bash
  sim_vehicle.py -L RATBeach -v ArduSub  --model=JSON --console
```

In another terminal run the simulation + mavros + agent:
```Bash
 ros2 launch tudelft_hackathon bluerov_bringup.launch.py simulation:=true ardusub:=false
```

**Comment by phamquandung** [comment]
Hi @Rezenders,

All is well now but I would like to remind you a bit in Dev container of VSCode. The user name is `docker` not `ros`. Thanks a lot for your help
